ALTER TABLE partner_listings
    ADD COLUMN IF NOT EXISTS price_per_day DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS location TEXT,
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS description TEXT;
